---
- name: add PPA
  apt_repository: repo=ppa:rwky/redis state=present

- name: update apt cache
  apt: update_cache=yes

- name: install redis-server
  apt: pkg=redis-server state=present

- name: start redis-server
  service: name=redis-server state=started
