---
- name: add PPA
  apt_repository: repo=ppa:nginx/stable state=present

- name: update apt cache
  apt: update_cache=yes

- name: install nginx
  apt: pkg=nginx state=present

- name: start nginx
  service: name=nginx state=started

- name: remove default site
  file: path=/etc/nginx/sites-enabled/default state=absent

- name: copy nginx.conf
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: copy site configuration
  template: src=discourse dest=/etc/nginx/sites-enabled/discourse
  notify: restart nginx
