---
- hosts: all
  sudo: True
  roles:
  - common

- hosts: redis
  sudo: True
  roles:
    - { role: redis, tags: ['redis'] }

- hosts: nginx
  sudo: True
  roles:
    - { role: nginx, tags: ['nginx'] }

- hosts: postgres
  sudo: True
  roles:
    - { role: postgres, tags: ['postgres'] }

- hosts: postgres
  sudo: True
  sudo_user: postgres
  tasks:
  - include: roles/postgres/tasks/setup_db.yml
    tags: ['postgres']

- hosts: discourse
  sudo: True
  roles:
    - { role: discourse, tags: ['discourse'] }
