- name: add New Relic apt repository
  get_url: dest=/etc/apt/sources.list.d/newrelic.list url=http://download.newrelic.com/debian/newrelic.list

- name: add New Relic key
  shell: apt-key adv --keyserver hkp://subkeys.pgp.net --recv-keys 548C16BF

- name: update apt cache
  apt: update_cache=yes

- name: install server monitor daemon
  apt: pkg=newrelic-sysmond state=present

- name: add license key
  shell: nrsysmond-config --set license_key={{newrelic_license_key}}

- name: start sysmond service
  service: name=newrelic-sysmond state=started

